install_missing_packages(c('googlesheets4','data.table','dplyr','flextable','RCurl','readr','gt','shiny','DT','quarto'))

library(googlesheets4)
library(data.table)
library(dplyr)
library(flextable)
library(RCurl)
library(readr)
library(gt)
library(shiny)
library(DT)
